//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.17 at 02:09:53 AM IST 
//


package com.dummy_core_bank.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fundTransferType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fromAccountNO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="toAccountNO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fundTransferType",
    "fromAccountNO",
    "toAccountNO"
})
@XmlRootElement(name = "fundTransferRequest")
public class FundTransferRequest {

    @XmlElement(required = true)
    protected String fundTransferType;
    @XmlElement(required = true)
    protected String fromAccountNO;
    @XmlElement(required = true)
    protected String toAccountNO;

    /**
     * Gets the value of the fundTransferType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFundTransferType() {
        return fundTransferType;
    }

    /**
     * Sets the value of the fundTransferType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFundTransferType(String value) {
        this.fundTransferType = value;
    }

    /**
     * Gets the value of the fromAccountNO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromAccountNO() {
        return fromAccountNO;
    }

    /**
     * Sets the value of the fromAccountNO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromAccountNO(String value) {
        this.fromAccountNO = value;
    }

    /**
     * Gets the value of the toAccountNO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToAccountNO() {
        return toAccountNO;
    }

    /**
     * Sets the value of the toAccountNO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToAccountNO(String value) {
        this.toAccountNO = value;
    }

}
