//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.16 at 09:49:24 PM IST 
//


package com.dummy_core_bank.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="totalBalanceInfo" type="{http://www.dummy-core-bank.com/ws}totalBalanceInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "totalBalanceInfo"
})
@XmlRootElement(name = "getAllAccountBalanceByUserIdResponse")
public class GetAllAccountBalanceByUserIdResponse {

    @XmlElement(required = true)
    protected TotalBalanceInfo totalBalanceInfo;

    /**
     * Gets the value of the totalBalanceInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TotalBalanceInfo }
     *     
     */
    public TotalBalanceInfo getTotalBalanceInfo() {
        return totalBalanceInfo;
    }

    /**
     * Sets the value of the totalBalanceInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TotalBalanceInfo }
     *     
     */
    public void setTotalBalanceInfo(TotalBalanceInfo value) {
        this.totalBalanceInfo = value;
    }

}
